# Generated by Django 2.2.9 on 2022-05-09 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220508_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'default_related_name': 'groups'},
        ),
    ]
